import { projects as raw } from './portfolioData.js';

export type Project = (typeof raw)[number] & {
  githubLink?: string;
  liveLinkLabel?: string;
};

export const projects = raw as Project[];

/** Responsive WebP sources generated by scripts/optimize-previews.mjs */
export const previewSources = (p: Project) => {
  const base = p.previewImage.replace(/\.png$/, '');
  return {
    srcset: `${base}-720.webp 720w, ${base}-1440.webp 1440w`,
    src: `${base}-720.webp`,
    fallback: p.previewImage,
    width: p.previewImageDimensions.width,
    height: p.previewImageDimensions.height,
  };
};

export const primaryTag = (p: Project) => p.tags[0];

/** A short category label for the index list. */
export const kindOf = (p: Project) => {
  const t = p.tags.join(' ').toLowerCase();
  if (/3d/.test(t)) return '3D experience';
  if (/stripe|matching|crm|dashboard|supabase/.test(t) && /react|next/.test(t)) return 'Web app';
  if (/mcp|python/.test(t)) return 'Open source';
  if (/bot|automation/.test(t)) return 'Automation';
  return 'Website';
};
